[tool.poetry]
name = "python_battleships"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pylint = "^2.3"
mypy = "^0.720.0"
autopep8 = "^1.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
